"""
Django settings for moc project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ''  # edit

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []  # edit

# Application definition

INSTALLED_APPS = [
    'mocbackend.apps.MocbackendConfig',
    'rest_framework',
    'django_rq',
    'rest_framework.authtoken',
    'snowpenguin.django.recaptcha2',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',
    'ckeditor',
    'jet',
    # 'corsheaders',  # edit
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    # 'corsheaders.middleware.CorsMiddleware',  # edit
    'mocbackend.middleware.RequestLocMemCacheMiddleware',
    'mocbackend.middleware.AccessLogMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_otp.middleware.OTPMiddleware',
]

ROOT_URLCONF = 'moc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'moc.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': '127.0.0.1',
        'PORT': '5432',
        'NAME': '',  # edit
        'USER': '',  # edit
        'PASSWORD': '',  # edit
        # 'OPTIONS': {
            # 'options': '-c search_path=moc',
        # },
        'ATOMIC_REQUESTS': True,
        'CONN_MAX_AGE': 300,
    }
}

ADDON_DATABASES = [
    {
        'BACKEND': 'mocbackend.databases.ElasticsearchDB',
        'HOST': '127.0.0.1',
        'PORT': '9200',
        'USE_SSL': False,
        'USER': '',  # edit
        'PASSWORD': '',  # edit
        'INDICES_PREFIX': 'mocbackend',
        'DOC_TYPE_NAME': 'default'
    },
    {
        'BACKEND': 'mocbackend.databases.Neo4jDB',
        'HOST': '127.0.0.1',
        'PORT': '7687',
        'USER': '',  # edit
        'PASSWORD': '',  # edit
    }
]

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

# edit
LANGUAGE_CODE = 'en-us'
# LANGUAGE_CODE = 'hr-hr'

# edit
# TIME_ZONE = 'UTC'
TIME_ZONE = 'Europe/Zagreb'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = True
CSRF_USE_SESSIONS = True
SESSION_COOKIE_SECURE = True

ADMINS = []  # edit

# http://www.django-rest-framework.org/api-guide/settings
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'rest_framework.authentication.SessionAuthentication',
        # 'rest_framework.authentication.BasicAuthentication',
        # 'rest_framework.authentication.TokenAuthentication',
        'mocbackend.authentication.QueryStringTokenAuthentication',
    ),
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '30/second',
        'user': '30/second'
    }
}

MOCBACKEND_DEFAULTS = {
    'FIXED_POINT_DECIMAL_PLACES': 2,
    'RANGE_FLOATING_POINT_FROM_INCLUSIVE': True,
    'RANGE_FLOATING_POINT_TO_INCLUSIVE': True,

    'API_GEO_VALUES_SEPARATOR': ', ',
    'API_RANGE_VALUES_SEPARATOR': ' -> ',
    'ADMIN_GEO_VALUES_SEPARATOR': ', ',
    'ADMIN_RANGE_VALUES_SEPARATOR': ' -> ',
}

JET_DEFAULT_THEME = 'light-gray'

# CORS_ORIGIN_WHITELIST = []

RQ_QUEUES = {
    'db': {
        'HOST': '127.0.0.1',
        'PORT': 6379,
        'DB': 0,
        'PASSWORD': '',  # edit
    },
    'elasticsearch': {
        'HOST': '127.0.0.1',
        'PORT': 6379,
        'DB': 0,
        'PASSWORD': '',  # edit
    },
    'neo4j': {
        'HOST': '127.0.0.1',
        'PORT': 6379,
        'DB': 0,
        'PASSWORD': '',  # edit
    },
    'system_mails': {
        'HOST': '127.0.0.1',
        'PORT': 6379,
        'DB': 0,
        'PASSWORD': '',  # edit
    },
    'notification_mails': {
        'HOST': '127.0.0.1',
        'PORT': 6379,
        'DB': 0,
        'PASSWORD': '',  # edit
    },
    'scheduler': {
        'HOST': '127.0.0.1',
        'PORT': 6379,
        'DB': 0,
        'PASSWORD': '',  # edit
    },
}
RQ_SHOW_ADMIN_LINK = True

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(name)s %(pathname)s:%(lineno)d %(funcName)s() %(message)s'
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse'
        }
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'filters': ['require_debug_false'],
            'class': 'logging.FileHandler',
            'filename': '',  # edit
            'formatter': 'verbose',
        }
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'mocbackend': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
    }
}

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Format'],
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter',
             'JustifyRight'],
            ['Link', 'Unlink'],
            ['RemoveFormat', 'Source'],
        ],
        'format_tags': 'p;h2;h3;div',
    }
}

OTP_TOTP_ISSUER = 'Mozaik veza'

RECAPTCHA_PUBLIC_KEY = ''  # edit
RECAPTCHA_PRIVATE_KEY = ''  # edit

EMAIL_HOST = ''  # edit
EMAIL_PORT = ''  # edit
EMAIL_HOST_USER = ''  # edit
EMAIL_HOST_PASSWORD = ''  # edit
# Note that EMAIL_USE_TLS/EMAIL_USE_SSL are mutually exclusive, so only set one of those settings to True.
EMAIL_USE_TLS = True  # edit
EMAIL_USE_SSL = False  # edit

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
    },
    'cron_update_dbs': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': '',  # edit
        'KEY_PREFIX': 'mocbackend'
    }
}
