# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocbackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticconnectiontype',
            name='reverse_name',
            field=models.CharField(max_length=128),
        ),
    ]
