# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-08 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocbackend', '0002_auto_20180228_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageentity',
            name='public_id',
            field=models.CharField(max_length=128, unique=True, verbose_name='Public ID'),
        ),
    ]
