# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-15 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mocbackend', '0004_auto_20180426_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageattribute',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='mocbackend.StageAttribute'),
        ),
        migrations.AlterIndexTogether(
            name='stageattribute',
            index_together=set([('deleted', 'published', 'string_id'), ('deleted', 'published', 'id'), ('deleted', 'published', 'attribute', 'id'), ('deleted', 'published', 'attribute', 'order_number'), ('deleted', 'published', 'attribute', 'string_id'), ('deleted', 'published', 'collection', 'order_number'), ('deleted', 'published', 'entity_type', 'id'), ('deleted', 'published', 'collection', 'string_id'), ('deleted', 'published', 'collection', 'id'), ('deleted', 'published', 'entity_type', 'string_id'), ('deleted', 'published', 'entity_type', 'order_number')]),
        ),
    ]
