# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-25 14:32
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocbackend', '0005_auto_20180615_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('content_short', ckeditor.fields.RichTextField(blank=True)),
                ('content_long', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
    ]
