# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mocbackend', '0008_auto_20180801_1405'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stageentity',
            unique_together=set([('internal_slug', 'internal_slug_count')]),
        ),
    ]
