# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 12:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('mocbackend', '0009_auto_20180801_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEntity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'mocbackend_user_entity',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_info', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('send_notification_on_change_watched_entity', models.BooleanField(default=False)),
                ('watched_entities', models.ManyToManyField(related_name='watchers', through='mocbackend.UserEntity', to='mocbackend.StageEntity')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'mocbackend_user_info',
            },
        ),
        migrations.CreateModel(
            name='UserSavedSearch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=64)),
                ('url', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to='mocbackend.UserInfo')),
            ],
            options={
                'verbose_name': 'Saved Search',
                'verbose_name_plural': 'Saved Searches',
                'db_table': 'mocbackend_user_saved_search',
            },
        ),
        migrations.AddField(
            model_name='userentity',
            name='backend_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backend_user_entities', to='mocbackend.UserInfo'),
        ),
        migrations.AddField(
            model_name='userentity',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_backend_users', to='mocbackend.StageEntity'),
        ),
        migrations.AlterUniqueTogether(
            name='usersavedsearch',
            unique_together=set([('owner', 'name'), ('owner', 'url')]),
        ),
        migrations.AlterIndexTogether(
            name='usersavedsearch',
            index_together=set([('owner', 'created_at')]),
        ),
        migrations.AlterUniqueTogether(
            name='userentity',
            unique_together=set([('backend_user', 'entity')]),
        ),
    ]
