# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-06 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocbackend', '0010_auto_20180802_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('remote_ip', models.GenericIPAddressField(db_index=True)),
                ('method', models.CharField(db_index=True, max_length=7)),
                ('path', models.TextField(db_index=True)),
                ('query', models.TextField(db_index=True)),
                ('post_data', models.TextField()),
                ('response_status_code', models.CharField(db_index=True, max_length=3)),
                ('request', models.TextField()),
                ('response', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Access Log',
                'verbose_name': 'Access Log',
                'db_table': 'logging_access_log',
            },
        ),
        migrations.AlterModelTable(
            name='article',
            table='cms_article',
        ),
        migrations.AlterIndexTogether(
            name='accesslog',
            index_together=set([('path', 'query')]),
        ),
    ]
