# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-10 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocbackend', '0011_auto_20180806_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageattribute',
            name='order_number',
            field=models.IntegerField(db_index=True, default=10000),
        ),
        migrations.AlterIndexTogether(
            name='stageattribute',
            index_together=set([('deleted', 'published', 'entity_type', 'id'), ('deleted', 'published', 'attribute', 'id'), ('deleted', 'published', 'collection', 'order_number'), ('deleted', 'published', 'collection', 'id'), ('deleted', 'published', 'collection', 'string_id'), ('deleted', 'published', 'attribute', 'string_id'), ('deleted', 'published', 'attribute', 'order_number'), ('deleted', 'published', 'entity_type', 'string_id'), ('deleted', 'published', 'entity_type', 'order_number'), ('deleted', 'published', 'order_number'), ('deleted', 'published', 'id'), ('deleted', 'published', 'string_id')]),
        ),
    ]
