# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mocbackend', '0013_auto_20180816_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userentity',
            old_name='backend_user',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='userentity',
            unique_together=set([('owner', 'entity')]),
        ),
    ]
