# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mocbackend', '0014_auto_20180816_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersavedsearch',
            old_name='url',
            new_name='saved_url',
        ),
        migrations.AlterUniqueTogether(
            name='usersavedsearch',
            unique_together=set([('owner', 'name'), ('owner', 'saved_url')]),
        ),
    ]
