# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-20 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mocbackend', '0015_auto_20180816_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentityentitychange',
            name='entity_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_entity_changes', to='mocbackend.StageEntityEntity'),
        ),
    ]
