# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-20 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mocbackend', '0016_auto_20180817_1410'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='logentityentitychange',
            index_together=set([('deleted', 'published', 'id')]),
        ),
    ]
