# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-20 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mocbackend', '0017_auto_20180820_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentityentitychange',
            name='connection_type',
        ),
        migrations.RemoveField(
            model_name='logentityentitychange',
            name='entity_a',
        ),
        migrations.RemoveField(
            model_name='logentityentitychange',
            name='entity_b',
        ),
        migrations.RemoveField(
            model_name='logentityentitychange',
            name='transaction_amount',
        ),
        migrations.RemoveField(
            model_name='logentityentitychange',
            name='transaction_currency',
        ),
        migrations.RemoveField(
            model_name='logentityentitychange',
            name='transaction_date',
        ),
    ]
