# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-23 13:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('mocbackend', '0018_auto_20180820_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityExtensionUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='security_extension', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('password_change_token_hash', models.CharField(default=None, max_length=128, null=True)),
                ('password_change_token_hash_salt', models.CharField(default=None, max_length=128, null=True)),
                ('password_change_token_created_at', models.DateTimeField(default=None, null=True)),
                ('unverified_email', models.EmailField(max_length=254)),
                ('email_verification_token_hash', models.CharField(default=None, max_length=128, null=True)),
                ('email_verification_token_hash_salt', models.CharField(default=None, max_length=128, null=True)),
                ('email_verification_token_created_at', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'verbose_name': 'Security Extension',
                'db_table': 'security_extension_user',
                'verbose_name_plural': 'Security Extensions',
            },
        ),
        migrations.RemoveField(
            model_name='stageentityentitycollection',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='stageentityentitycollection',
            name='valid_to',
        ),
        migrations.AddField(
            model_name='stageentityentity',
            name='valid_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stageentityentity',
            name='valid_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
