# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocbackend', '0019_auto_20180823_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagecollection',
            name='quality',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stagesource',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
