# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-31 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mocbackend', '0020_auto_20180830_1441'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stageentityentity',
            unique_together=set([('entity_a', 'entity_b', 'connection_type', 'valid_from', 'valid_to', 'transaction_amount', 'transaction_currency', 'transaction_date')]),
        ),
        migrations.AlterIndexTogether(
            name='stageentityentity',
            index_together=set([('deleted', 'published', 'entity_b', 'entity_a', 'connection_type', 'valid_from', 'valid_to'), ('deleted', 'published', 'entity_a', 'entity_b', 'connection_type', 'valid_from', 'valid_to')]),
        ),
    ]
