# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-14 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocbackend', '0021_auto_20180831_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageattributetype',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Soft Deleted'),
        ),
        migrations.AlterField(
            model_name='stageentity',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Soft Deleted'),
        ),
        migrations.AlterIndexTogether(
            name='stageattribute',
            index_together=set([('deleted', 'published', 'collection', 'order_number'), ('deleted', 'published', 'string_id'), ('deleted', 'published', 'attribute', 'id'), ('deleted', 'published', 'attribute', 'order_number'), ('deleted', 'published', 'entity_type', 'id'), ('deleted', 'published', 'collection', 'id'), ('deleted', 'published', 'order_number'), ('deleted', 'published', 'id'), ('deleted', 'published', 'attribute', 'string_id'), ('deleted', 'published', 'entity_type', 'order_number'), ('deleted', 'string_id', 'attribute', 'attribute_type'), ('deleted', 'published', 'entity_type', 'string_id'), ('deleted', 'published', 'collection', 'string_id')]),
        ),
        migrations.AlterIndexTogether(
            name='stageattributevalue',
            index_together=set([('deleted', 'attribute', 'value_string'), ('deleted', 'published', 'attribute', 'entity'), ('deleted', 'published', 'attribute', 'entity_entity'), ('deleted', 'published', 'id')]),
        ),
        migrations.AlterIndexTogether(
            name='stageentity',
            index_together=set([('deleted', 'internal_slug'), ('deleted', 'published', 'public_id'), ('force_pep', 'deleted', 'published', 'public_id'), ('linked_potentially_pep', 'deleted', 'published', 'public_id'), ('linked_potentially_pep', 'deleted', 'published', 'id'), ('deleted', 'published', 'id'), ('force_pep', 'deleted', 'published', 'id')]),
        ),
    ]
