# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mocbackend', '0022_auto_20180914_1039'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stageattribute',
            unique_together=set([]),
        ),
    ]
