# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mocbackend', '0023_auto_20180923_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageattribute',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='mocbackend.StageAttribute'),
        ),
    ]
