# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-22 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mocbackend', '0025_auto_20181022_1433'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='stageattributevalue',
            index_together=set([('attribute', 'entity_entity'), ('deleted', 'published', 'attribute', 'entity'), ('deleted', 'attribute', 'value_string'), ('deleted', 'published', 'id'), ('deleted', 'published', 'attribute', 'entity_entity'), ('attribute', 'entity')]),
        ),
    ]
