# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocbackend', '0027_auto_20181022_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageattribute',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
