# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mocbackend', '0029_auto_20181113_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stageattributevalue',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='stageattributevalue',
            name='published',
        ),
    ]
