# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-22 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mocbackend', '0030_auto_20181113_1835'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='logchangeset',
            index_together=set([('deleted', 'published', 'collection', 'created_at')]),
        ),
    ]
