# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-23 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocbackend', '0034_auto_20181122_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagecollection',
            name='last_in_log',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='stagesource',
            name='last_in_log',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
    ]
