# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-24 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mocbackend', '0035_auto_20181123_2031'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='stageattribute',
            index_together=set([('deleted', 'published', 'id'), ('deleted', 'published', 'string_id'), ('deleted', 'published', 'entity_type', 'id'), ('deleted', 'published', 'entity_type', 'string_id'), ('deleted', 'published', 'attribute', 'order_number'), ('string_id', 'attribute'), ('deleted', 'published', 'collection', 'string_id'), ('deleted', 'published', 'attribute', 'id'), ('deleted', 'published', 'entity_type', 'order_number'), ('deleted', 'published', 'order_number'), ('deleted', 'string_id', 'attribute', 'attribute_type'), ('deleted', 'published', 'collection', 'order_number'), ('entity_type', 'attribute_type'), ('deleted', 'published', 'attribute', 'string_id'), ('deleted', 'published', 'collection', 'id')]),
        ),
    ]
