# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-16 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mocbackend', '0036_auto_20181124_1430'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='stageattribute',
            index_together=set([('deleted', 'published', 'entity_type', 'string_id'), ('deleted', 'published', 'order_number'), ('deleted', 'published', 'entity_type', 'order_number'), ('collection', 'attribute'), ('deleted', 'published', 'attribute', 'order_number'), ('deleted', 'published', 'attribute', 'string_id'), ('deleted', 'string_id', 'attribute', 'attribute_type'), ('deleted', 'published', 'entity_type', 'id'), ('deleted', 'published', 'collection', 'string_id'), ('string_id', 'attribute'), ('deleted', 'published', 'collection', 'order_number'), ('entity_type', 'attribute_type'), ('deleted', 'published', 'id'), ('deleted', 'published', 'collection', 'id'), ('deleted', 'published', 'attribute', 'id'), ('deleted', 'published', 'string_id')]),
        ),
    ]
