# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-19 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocbackend', '0037_auto_20190116_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageattribute',
            name='all_parents_published',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='stageattribute',
            name='any_parent_deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
