# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-21 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocbackend', '0038_auto_20190119_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageattribute',
            name='all_parents_all_related_published',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='stageattribute',
            name='all_related_published',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='stageattribute',
            name='any_parent_any_related_deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='stageattribute',
            name='any_related_deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='stageattribute',
            name='finally_deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='stageattribute',
            name='finally_published',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterIndexTogether(
            name='stageattribute',
            index_together=set([('finally_deleted', 'finally_published', 'attribute', 'string_id'), ('finally_deleted', 'finally_published', 'attribute', 'order_number'), ('finally_deleted', 'string_id', 'attribute', 'attribute_type'), ('collection', 'attribute'), ('finally_deleted', 'finally_published', 'entity_type', 'order_number'), ('string_id', 'attribute'), ('finally_deleted', 'finally_published', 'entity_type', 'string_id'), ('finally_deleted', 'finally_published', 'collection', 'string_id'), ('finally_deleted', 'finally_published', 'collection', 'order_number'), ('finally_deleted', 'finally_published', 'string_id'), ('entity_type', 'attribute_type'), ('finally_deleted', 'finally_published', 'id'), ('finally_deleted', 'finally_published', 'entity_type', 'id'), ('finally_deleted', 'finally_published', 'collection', 'id'), ('finally_deleted', 'finally_published', 'attribute', 'id'), ('finally_deleted', 'finally_published', 'order_number')]),
        ),
    ]
